In [2]:
import numpy as np
import pandas as pd

In [3]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [4]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movies.merge(credits,on='title')

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [7]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [8]:
#genres
#id
#keywords
#title
#overview

In [9]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [10]:
movies=movies[['id','title','overview','genres','keywords']]

In [11]:
movies.head()

,id,title,overview,genres,keywords
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":..."

In [12]:
movies.isnull().sum()

id          0
title       0
overview    3
genres      0
keywords    0
dtype: int64

In [13]:
movies.dropna(inplace=True)

In [14]:
movies.duplicated().sum()

np.int64(0)

In [15]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [16]:
#[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
# to be converted into ['Action','Adventure','Fantasy'.'Science Fiction']

In [17]:
 # as it a list of strings we cannot print the values of key 'name'
# so there is a module in python called as ast
#And a method in ast called as ast.literal_eval() which converts the string into a list

In [30]:
import ast
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [19]:
convert('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [20]:
#this was just for 1 row of genres

In [23]:
#now we will apply this for the entire rows of genre
movies['genres']=movies['genres'].apply(convert)

In [24]:
movies.head()

,id,title,overview,genres,keywords
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":..."

In [25]:
movies['keywords']= movies['keywords'].apply(convert)

In [26]:
movies.head()

,id,title,overview,genres,keywords
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel..."

In [31]:
#for first 3 values of cast feature
import ast
def convert(obj):
    counter = 0
    L=[]
    for i in ast.literal_eval(obj):
        if counter != 3:
           L.append(i['name'])
           counter+=1
        else:
            break
    return L

In [32]:
 #movies['cast']= movies['cast'].apply(convert)

In [33]:
# for crew
# we only need the name of the director
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if(i['job']=='Director'):
            L.append(i['name'])
            break
    return L

In [34]:
#movies['crew']= movies['crew'].apply(fetch_director)

In [37]:
#overview feature is a string so we need to convert it into a list as well
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [42]:
movies.head()

,id,title,overview,genres,keywords
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel..."

In [43]:
#in cast 
#convert 'Sam Worthington' into 'SamWorthington'
#remove the space between words because [Sam] can also be someone elses name

In [49]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
#movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
#movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [50]:
movies.head()

,id,title,overview,genres,keywords
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p..."

In [51]:
# we are going to make a separate column called as Tag column 
#in which we are going to concatenate overview, genres, keywords together
movies['tag']= movies['overview']+movies['keywords']+movies['genres']#+movies['cast'+movies['crew']]

In [52]:
movies.head()

,id,title,overview,genres,keywords,tag
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili..."

In [53]:
new_df = movies[['id','title','tag']]

In [55]:
new_df

,id,title,tag
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4798,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4799,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4800,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4801,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4802,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [56]:
#now we will convert the list in Tag feature into a string
new_df['tag']= new_df['tag'].apply(lambda x: " ".join(x))

C:\Users\krish\AppData\Local\Temp\ipykernel_13376\3727556927.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag']= new_df['tag'].apply(lambda x: " ".join(x))

In [59]:
new_df.head()

,id,title,tag
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [60]:
new_df['tag'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d Action Adventure Fantasy ScienceFiction'

In [61]:
#convert everything in the Tag feature into lowercase
new_df['tag']= new_df['tag'].apply(lambda x: x.lower())

C:\Users\krish\AppData\Local\Temp\ipykernel_13376\1023126546.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag']= new_df['tag'].apply(lambda x: x.lower())

In [72]:
new_df.head()

,id,title,tag
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [73]:
  # vectors
# as we have a data of 5000 movies and by any chance if we like 1 movie 
# and if we want to recommend more movies , WE WILL LOOK FOR THE CLOSEST MOVIE VECTOR 
# OF THAT MOVIE

In [74]:
# We will have too convert the text in the Tag feature into Vectors 
# This process is called as Text Vectorisation
# The technique we use for this is called as Bag of Words
# There are other techniques as well like 1) tfidf 2)wordevec

In [75]:
# Step 1) Concatenate all the Tag Features of every Row [Concan_Tags]
# Step 2) Find 5000 most used words
# Step 3) extract those most used words
# Step 4) Choose the Tag of any 1 movie and calculate the frequency of all the words in the Tag eg)'Action' or 'frequency'
#  |W1|W2|W3|W4|........|W5000|
#  |2 |3 |0 |1|..........|2435|  ---> this is a vector now
# Now we have a dataframe of the frequencies of each word in a row
# a dimension of 5000 is created , so it is considered a good practice if u use a lower number of dimension

In [76]:
# When we are performing vectorisation , dont consider 'STOP' words
# STOP words mean which are used for sentence formation but do not have any
# contribution in the meaning of the sentence for example)in,are,is,or,and, from

In [81]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Downloading scikit_learn-1.6.0-cp313-cp313-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\krish\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.2.0)
Collecting scipy>=1.6.0 (from scikit-learn)
  Downloading scipy-1.14.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.6.0-cp313-cp313-win_amd64.whl (11.1 MB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/11.1 MB 8.1 MB/s eta 0:00:02
   ------------ --------------------------- 3.4/11.1 MB 8.3 MB/s eta 0:00:01
   ------------------ --------------------- 5.0/11.1 MB 8.1 MB/s eta 0:00:01
   ------------------------ --------------- 6.8/11.1 MB 8.3 MB/s eta 0:00:01
   ----------------------------- ---------- 8.1/11.1 MB 8.1 MB/s eta 0:00:01
   ----------------------------------- ---- 9.7/11.1 MB 8.0 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.1 MB 7.8 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 7.6 MB/s eta 0:00:00
Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
Downloading scipy-1.14.1-cp313-cp313-win_amd64.whl (44.5 MB)
   ---------------------------------------- 0.0/44.5 MB ? eta -:--:--
   - -------------------------------------- 1.8/44.5 MB 8.7 MB/s eta 0:00:05
   --- ------------------------------------ 3.9/44.5 MB 9.7 MB/s eta 0:00:05
   ----- ---------------------------------- 5.8/44.5 MB 9.7 MB/s eta 0:00:05
   ----- ---------------------------------- 6.6/44.5 MB 7.7 MB/s eta 0:00:05
   ------- -------------------------------- 7.9/44.5 MB 7.4 MB/s eta 0:00:05
   -------- ------------------------------- 10.0/44.5 MB 7.7 MB/s eta 0:00:05
   ---------- ----------------------------- 12.1/44.5 MB 8.0 MB/s eta 0:00:05
   ------------ --------------------------- 14.2/44.5 MB 8.2 MB/s eta 0:00:04
   -------------- ------------------------- 16.5/44.5 MB 8.6 MB/s eta 0:00:04
   ---------------- ----------------------- 18.9/44.5 MB 8.8 MB/s eta 0:00:03
   ------------------- -------------------- 21.2/44.5 MB 9.0 MB/s eta 0:00:03
   -------------------- ------------------- 23.3/44.5 MB 9.2 MB/s eta 0:00:03
   ---------------------- ----------------- 24.9/44.5 MB 9.3 MB/s eta 0:00:03
   ----------------------- ---------------- 26.5/44.5 MB 8.9 MB/s eta 0:00:03
   ------------------------- -------------- 28.6/44.5 MB 8.9 MB/s eta 0:00:02
   --------------------------- ------------ 30.1/44.5 MB 8.9 MB/s eta 0:00:02
   ---------------------------- ----------- 32.0/44.5 MB 8.8 MB/s eta 0:00:02
   ------------------------------ --------- 34.1/44.5 MB 8.9 MB/s eta 0:00:02
   -------------------------------- ------- 36.2/44.5 MB 9.0 MB/s eta 0:00:01
   ---------------------------------- ----- 38.0/44.5 MB 9.0 MB/s eta 0:00:01
   ----------------------------------- ---- 39.8/44.5 MB 9.0 MB/s eta 0:00:01
   ------------------------------------- -- 41.7/44.5 MB 8.9 MB/s eta 0:00:01
   ---------------------------------------  44.0/44.5 MB 9.0 MB/s eta 0:00:01
   ---------------------------------------- 44.5/44.5 MB 8.9 MB/s eta 0:00:00
Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.4.2 scikit-learn-1.6.0 scipy-1.14.1 threadpoolctl-3.5.0

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [95]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [96]:
vectors = cv.fit_transform(new_df['tag']).toarray()

In [97]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4800, 5000))

In [98]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [102]:
cv.get_feature_names()

AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'

In [ ]:
# stemming
# ['loved', 'loving','lovely'] ----> ['love','love','love']

In [103]:
!pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Collecting nltk
  Downloading nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting click (from nltk)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: joblib in c:\users\krish\appdata\roaming\python\python313\site-packages (from nltk) (1.4.2)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2024.11.6-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in c:\users\krish\appdata\roaming\python\python313\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.1-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------- ----- 1.3/1.5 MB 10.8 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 4.5 MB/s eta 0:00:00
Downloading regex-2024.11.6-cp313-cp313-win_amd64.whl (273 kB)
Downloading click-8.1.7-py3-none-any.whl (97 kB)
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, regex, click, nltk
Successfully installed click-8.1.7 nltk-3.9.1 regex-2024.11.6 tqdm-4.67.1

  WARNING: The script tqdm.exe is installed in 'C:\Users\krish\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script nltk.exe is installed in 'C:\Users\krish\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [104]:
import nltk

In [105]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [111]:
def stem(text):
    y=[]

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [108]:
ps.stem('loved')

'love'

In [109]:
ps.stem('lovely')

'love'

In [112]:
new_df['tag'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d action adventure fantasy sciencefiction'

In [113]:
stem(
'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d action adventure fantasy sciencefiction')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d action adventur fantasi sciencefict'

In [116]:
new_df['tag'] = new_df['tag'].apply(stem)

C:\Users\krish\AppData\Local\Temp\ipykernel_13376\4074900442.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag'] = new_df['tag'].apply(stem)

In [117]:
new_df

,id,title,tag
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4798,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4799,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4800,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4801,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4802,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [118]:
# we have to calculate distaance between 2 vectors
# more the distance less is the similarity 
# eucledian distance is the diswtance between tip of 2 vectors [not to be used in higher dimensions]
# while cosine distance is the angle between 2 vectors

In [119]:
from sklearn.metrics.pairwise import cosine_similarity

In [121]:
similarity = cosine_similarity(vectors)

In [122]:
similarity

array([[1.        , 0.09583148, 0.06277648, ..., 0.02465568, 0.0270666 ,
        0.        ],
       [0.09583148, 1.        , 0.07018624, ..., 0.02756589, 0.        ,
        0.        ],
       [0.06277648, 0.07018624, 1.        , ..., 0.02708645, 0.        ,
        0.        ],
       ...,
       [0.02465568, 0.02756589, 0.02708645, ..., 1.        , 0.07007128,
        0.04732485],
       [0.0270666 , 0.        , 0.        , ..., 0.07007128, 1.        ,
        0.05195243],
       [0.        , 0.        , 0.        , ..., 0.04732485, 0.05195243,
        1.        ]], shape=(4800, 4800))

In [123]:
similarity.shape

(4800, 4800)

In [128]:
similarity[0]

array([1.        , 0.09583148, 0.06277648, ..., 0.02465568, 0.0270666 ,
       0.        ], shape=(4800,))

In [129]:
similarity[1]

array([0.09583148, 1.        , 0.07018624, ..., 0.02756589, 0.        ,
       0.        ], shape=(4800,))

In [132]:
# procedure of getting the index
new_df[new_df['title']=='Batman Begins'].index[0]

np.int64(119)

In [134]:
# procedure to sort without losing the index
enumerate(similarity[0])
# we get an object as a result

In [135]:
list(enumerate(similarity[0]))

[(0, np.float64(1.0)),
 (1, np.float64(0.09583148474999097)),
 (2, np.float64(0.06277648205743444)),
 (3, np.float64(0.040996003084539386)),
 (4, np.float64(0.18043874177926345)),
 (5, np.float64(0.12327841818038447)),
 (6, np.float64(0.020060271357125983)),
 (7, np.float64(0.1825741858350554)),
 (8, np.float64(0.06506000486323554)),
 (9, np.float64(0.07824607964359516)),
 (10, np.float64(0.12143534814378325)),
 (11, np.float64(0.08336550215650926)),
 (12, np.float64(0.10350983390135313)),
 (13, np.float64(0.04829452884162951)),
 (14, np.float64(0.11769797726729994)),
 (15, np.float64(0.04600437062282361)),
 (16, np.float64(0.0857142857142857)),
 (17, np.float64(0.15275252316519466)),
 (18, np.float64(0.11501092655705902)),
 (19, np.float64(0.08728715609439694)),
 (20, np.float64(0.05855400437691198)),
 (21, np.float64(0.09759000729485331)),
 (22, np.float64(0.07207499701564471)),
 (23, np.float64(0.10141851056742199)),
 (24, np.float64(0.05884898863364997)),
 (25, np.float64(0.036454130828824455)),
 (26, np.float64(0.1739313106957345)),
 (27, np.float64(0.18070158058105024)),
 (28, np.float64(0.12555296411486888)),
 (29, np.float64(0.07319250547113999)),
 (30, np.float64(0.07559289460184544)),
 (31, np.float64(0.16903085094570333)),
 (32, np.float64(0.09376144618769908)),
 (33, np.float64(0.11338934190276817)),
 (34, np.float64(0.0)),
 (35, np.float64(0.1057361065275362)),
 (36, np.float64(0.18708286933869706)),
 (37, np.float64(0.08827348295047496)),
 (38, np.float64(0.06338656910463875)),
 (39, np.float64(0.09107651110783743)),
 (40, np.float64(0.05797710356524483)),
 (41, np.float64(0.1511857892036909)),
 (42, np.float64(0.0)),
 (43, np.float64(0.09968895725584535)),
 (44, np.float64(0.04364357804719847)),
 (45, np.float64(0.09116846116771035)),
 (46, np.float64(0.18832944617230335)),
 (47, np.float64(0.1980534816610477)),
 (48, np.float64(0.06900655593423541)),
 (49, np.float64(0.06629935441317959)),
 (50, np.float64(0.12777531299998796)),
 (51, np.float64(0.08024108542850393)),
 (52, np.float64(0.1690308509457033)),
 (53, np.float64(0.05096471914376255)),
 (54, np.float64(0.035245368842512066)),
 (55, np.float64(0.07755667343294811)),
 (56, np.float64(0.15118578920369088)),
 (57, np.float64(0.028571428571428567)),
 (58, np.float64(0.04829452884162951)),
 (59, np.float64(0.08139569275564795)),
 (60, np.float64(0.026398183867422733)),
 (61, np.float64(0.23904572186687872)),
 (62, np.float64(0.08451542547285165)),
 (63, np.float64(0.08518354199999197)),
 (64, np.float64(0.033806170189140665)),
 (65, np.float64(0.02164218276749025)),
 (66, np.float64(0.02519763153394848)),
 (67, np.float64(0.17928429140015903)),
 (68, np.float64(0.14098147537004826)),
 (69, np.float64(0.05175491695067656)),
 (70, np.float64(0.0857142857142857)),
 (71, np.float64(0.09107651110783743)),
 (72, np.float64(0.12344267996967351)),
 (73, np.float64(0.03877833671647406)),
 (74, np.float64(0.23199266800191018)),
 (75, np.float64(0.09107651110783743)),
 (76, np.float64(0.08017837257372731)),
 (77, np.float64(0.014824986333222025)),
 (78, np.float64(0.052796367734845466)),
 (79, np.float64(0.08017837257372731)),
 (80, np.float64(0.03505536546997459)),
 (81, np.float64(0.11710800875382396)),
 (82, np.float64(0.08451542547285165)),
 (83, np.float64(0.22430015382565205)),
 (84, np.float64(0.14675987714106856)),
 (85, np.float64(0.10811249552346705)),
 (86, np.float64(0.08696565534786725)),
 (87, np.float64(0.11595420713048966)),
 (88, np.float64(0.09107651110783743)),
 (89, np.float64(0.06121333677828399)),
 (90, np.float64(0.06506000486323554)),
 (91, np.float64(0.16574838603294897)),
 (92, np.float64(0.07100716024967263)),
 (93, np.float64(0.0515539262226467)),
 (94, np.float64(0.13522468075656266)),
 (95, np.float64(0.13041013273932528)),
 (96, np.float64(0.09759000729485331)),
 (97, np.float64(0.07396705090823068)),
 (98, np.float64(0.08696565534786725)),
 (99, np.float64(0.027066598098038335)),
 (100, np.float64(0.07968190728895957)),
 (101, np.float64(0.09258200997725513)),
 (102, np.float64(0.11194341570991125)),
 (103, np.float64(0.089554732567929)),
 (104, np.float64(0.060717674071891624)),
 (105, np.float64(0.11338934190276817)),
 (106, np.float64(0.04600437062282361)),
 (107, np.float64(0.09287269204251442)),
 (108, np.float64(0.16903085094570328)),
 (109, np.float64(0.07968190728895957)),
 (110, np.float64(0.02519763153394848)),
 (111, np.float64(0.15430334996209188)),
 (112, np.float64(0.09583148474999097)),
 (113, np.float64(0.05413319619607667)),
 (114, np.float64(0.05345224838248488)),
 (115, np.float64(0.057142857142857134)),
 (116, np.float64(0.057142857142857134)),
 (117, np.float64(0.06277648205743444)),
 (118, np.float64(0.017434201093860163)),
 (119, np.float64(0.04984447862792268)),
 (120, np.float64(0.0)),
 (121, np.float64(0.09416472308615166)),
 (122, np.float64(0.0994490316197694)),
 (123, np.float64(0.1246111965698067)),
 (124, np.float64(0.06837634587578276)),
 (125, np.float64(0.07813453848974923)),
 (126, np.float64(0.11952286093343935)),
 (127, np.float64(0.13848495294356286)),
 (128, np.float64(0.0)),
 (129, np.float64(0.10826639239215334)),
 (130, np.float64(0.03194382824999699)),
 (131, np.float64(0.11428571428571427)),
 (132, np.float64(0.04438967616184752)),
 (133, np.float64(0.033149677206589796)),
 (134, np.float64(0.14098147537004826)),
 (135, np.float64(0.0)),
 (136, np.float64(0.024397501823713332)),
 (137, np.float64(0.034868402187720325)),
 (138, np.float64(0.08336550215650926)),
 (139, np.float64(0.10821091383745127)),
 (140, np.float64(0.052796367734845466)),
 (141, np.float64(0.11633501014942217)),
 (142, np.float64(0.09258200997725513)),
 (143, np.float64(0.06965451903188581)),
 (144, np.float64(0.05484084971070818)),
 (145, np.float64(0.023002185311411804)),
 (146, np.float64(0.0173421993904824)),
 (147, np.float64(0.06506000486323554)),
 (148, np.float64(0.10811249552346706)),
 (149, np.float64(0.1760475392542646)),
 (150, np.float64(0.1980534816610477)),
 (151, np.float64(0.21128856368212912)),
 (152, np.float64(0.06629935441317959)),
 (153, np.float64(0.08728715609439694)),
 (154, np.float64(0.035245368842512066)),
 (155, np.float64(0.0)),
 (156, np.float64(0.06658451424277127)),
 (157, np.float64(0.11338934190276817)),
 (158, np.float64(0.15649215928719035)),
 (159, np.float64(0.07377111135633174)),
 (160, np.float64(0.09694584179118515)),
 (161, np.float64(0.036037498507822355)),
 (162, np.float64(0.03877833671647406)),
 (163, np.float64(0.05484084971070818)),
 (164, np.float64(0.09583148474999097)),
 (165, np.float64(0.05039526306789696)),
 (166, np.float64(0.12143534814378325)),
 (167, np.float64(0.07207499701564471)),
 (168, np.float64(0.16239958858823)),
 (169, np.float64(0.12198750911856666)),
 (170, np.float64(0.09287269204251442)),
 (171, np.float64(0.030358837035945812)),
 (172, np.float64(0.15511334686589623)),
 (173, np.float64(0.025482359571881275)),
 (174, np.float64(0.11428571428571427)),
 (175, np.float64(0.052796367734845466)),
 (176, np.float64(0.03194382824999699)),
 (177, np.float64(0.0)),
 (178, np.float64(0.026398183867422733)),
 (179, np.float64(0.07755667343294811)),
 (180, np.float64(0.02366905341655754)),
 (181, np.float64(0.023904572186687872)),
 (182, np.float64(0.10968169942141635)),
 (183, np.float64(0.07559289460184544)),
 (184, np.float64(0.1825741858350554)),
 (185, np.float64(0.05797710356524483)),
 (186, np.float64(0.040996003084539386)),
 (187, np.float64(0.1389425035941821)),
 (188, np.float64(0.023218173010628604)),
 (189, np.float64(0.08728715609439694)),
 (190, np.float64(0.08451542547285165)),
 (191, np.float64(0.052796367734845466)),
 (192, np.float64(0.0)),
 (193, np.float64(0.08877935232369503)),
 (194, np.float64(0.0)),
 (195, np.float64(0.06761234037828133)),
 (196, np.float64(0.059761430466719674)),
 (197, np.float64(0.04931136727215379)),
 (198, np.float64(0.06277648205743444)),
 (199, np.float64(0.1183452670827877)),
 (200, np.float64(0.08199200616907877)),
 (201, np.float64(0.0)),
 (202, np.float64(0.036037498507822355)),
 (203, np.float64(0.09416472308615166)),
 (204, np.float64(0.02519763153394848)),
 (205, np.float64(0.08728715609439694)),
 (206, np.float64(0.09221388919541468)),
 (207, np.float64(0.08696565534786725)),
 (208, np.float64(0.18070158058105024)),
 (209, np.float64(0.03877833671647406)),
 (210, np.float64(0.05484084971070818)),
 (211, np.float64(0.027788500718836418)),
 (212, np.float64(0.07644707871564382)),
 (213, np.float64(0.06601782722034923)),
 (214, np.float64(0.030358837035945812)),
 (215, np.float64(0.07476671794188401)),
 (216, np.float64(0.06629935441317959)),
 (217, np.float64(0.04643634602125721)),
 (218, np.float64(0.04517539514526256)),
 (219, np.float64(0.07049073768502413)),
 (220, np.float64(0.19518001458970663)),
 (221, np.float64(0.02519763153394848)),
 (222, np.float64(0.09116846116771035)),
 (223, np.float64(0.0857142857142857)),
 (224, np.float64(0.06440081861116377)),
 (225, np.float64(0.05413319619607667)),
 (226, np.float64(0.03194382824999699)),
 (227, np.float64(0.0994490316197694)),
 (228, np.float64(0.12888481555661674)),
 (229, np.float64(0.07705141285294194)),
 (230, np.float64(0.08322503785764788)),
 (231, np.float64(0.0)),
 (232, np.float64(0.12555296411486888)),
 (233, np.float64(0.11065666703449761)),
 (234, np.float64(0.06965451903188581)),
 (235, np.float64(0.05884898863364997)),
 (236, np.float64(0.10141851056742199)),
 (237, np.float64(0.07377111135633174)),
 (238, np.float64(0.11952286093343936)),
 (239, np.float64(0.10910894511799618)),
 (240, np.float64(0.05096471914376255)),
 (241, np.float64(0.08451542547285165)),
 (242, np.float64(0.09759000729485331)),
 (243, np.float64(0.1031078524452934)),
 (244, np.float64(0.06506000486323554)),
 (245, np.float64(0.09258200997725513)),
 (246, np.float64(0.06716604942594674)),
 (247, np.float64(0.0)),
 (248, np.float64(0.04829452884162951)),
 (249, np.float64(0.14754222271266348)),
 (250, np.float64(0.0)),
 (251, np.float64(0.04688072309384954)),
 (252, np.float64(0.023218173010628604)),
 (253, np.float64(0.06601782722034923)),
 (254, np.float64(0.08226127456606226)),
 (255, np.float64(0.0)),
 (256, np.float64(0.08199200616907877)),
 (257, np.float64(0.08827348295047496)),
 (258, np.float64(0.02366905341655754)),
 (259, np.float64(0.06629935441317959)),
 (260, np.float64(0.24688535993934702)),
 (261, np.float64(0.026082026547865053)),
 (262, np.float64(0.07319250547113999)),
 (263, np.float64(0.10811249552346706)),
 (264, np.float64(0.0)),
 (265, np.float64(0.030358837035945812)),
 (266, np.float64(0.1126872339638022)),
 (267, np.float64(0.07755667343294811)),
 (268, np.float64(0.02817180849095055)),
 (269, np.float64(0.033149677206589796)),
 (270, np.float64(0.10559273546969093)),
 (271, np.float64(0.08226127456606226)),
 (272, np.float64(0.03138824102871722)),
 (273, np.float64(0.024147264420814756)),
 (274, np.float64(0.08021849185198157)),
 (275, np.float64(0.13259870882635919)),
 (276, np.float64(0.07207499701564471)),
 (277, np.float64(0.06716604942594674)),
 (278, np.float64(0.13199091933711365)),
 (279, np.float64(0.10432810619146021)),
 (280, np.float64(0.0)),
 (281, np.float64(0.07396705090823068)),
 (282, np.float64(0.03138824102871722)),
 (283, np.float64(0.0)),
 (284, np.float64(0.020348923188911988)),
 (285, np.float64(0.023218173010628604)),
 (286, np.float64(0.02258769757263128)),
 (287, np.float64(0.028571428571428567)),
 (288, np.float64(0.0)),
 (289, np.float64(0.05096471914376255)),
 (290, np.float64(0.07049073768502413)),
 (291, np.float64(0.05413319619607667)),
 (292, np.float64(0.10350983390135313)),
 (293, np.float64(0.03253000243161777)),
 (294, np.float64(0.12555296411486888)),
 (295, np.float64(0.11428571428571428)),
 (296, np.float64(0.040697846377823976)),
 (297, np.float64(0.04829452884162951)),
 (298, np.float64(0.0)),
 (299, np.float64(0.04259177099999598)),
 (300, np.float64(0.18478728707195913)),
 (301, np.float64(0.1858536462519902)),
 (302, np.float64(0.059761430466719674)),
 (303, np.float64(0.030358837035945812)),
 (304, np.float64(0.07248803762927497)),
 (305, np.float64(0.19477964490741226)),
 (306, np.float64(0.09416472308615166)),
 (307, np.float64(0.1057361065275362)),
 (308, np.float64(0.07049073768502413)),
 (309, np.float64(0.06629935441317959)),
 (310, np.float64(0.036037498507822355)),
 (311, np.float64(0.1583891032045364)),
 (312, np.float64(0.11595420713048966)),
 (313, np.float64(0.07968190728895957)),
 (314, np.float64(0.0)),
 (315, np.float64(0.09583148474999097)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.07755667343294811)),
 (320, np.float64(0.03450327796711771)),
 (321, np.float64(0.0)),
 (322, np.float64(0.2253744679276044)),
 (323, np.float64(0.033149677206589796)),
 (324, np.float64(0.026398183867422733)),
 (325, np.float64(0.10811249552346706)),
 (326, np.float64(0.060717674071891624)),
 (327, np.float64(0.030358837035945812)),
 (328, np.float64(0.0)),
 (329, np.float64(0.08827348295047496)),
 (330, np.float64(0.11595420713048966)),
 (331, np.float64(0.05096471914376255)),
 (332, np.float64(0.14712247158412492)),
 (333, np.float64(0.03138824102871722)),
 (334, np.float64(0.11115400287534567)),
 (335, np.float64(0.0563436169819011)),
 (336, np.float64(0.07755667343294811)),
 (337, np.float64(0.024147264420814756)),
 (338, np.float64(0.0)),
 (339, np.float64(0.059761430466719674)),
 (340, np.float64(0.052796367734845466)),
 (341, np.float64(0.06506000486323554)),
 (342, np.float64(0.13848495294356286)),
 (343, np.float64(0.023002185311411804)),
 (344, np.float64(0.033806170189140665)),
 (345, np.float64(0.024147264420814756)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0)),
 (348, np.float64(0.06761234037828133)),
 (349, np.float64(0.0994490316197694)),
 (350, np.float64(0.055577001437672836)),
 (351, np.float64(0.0)),
 (352, np.float64(0.030358837035945812)),
 (353, np.float64(0.02519763153394848)),
 (354, np.float64(0.0)),
 (355, np.float64(0.040996003084539386)),
 (356, np.float64(0.09583148474999097)),
 (357, np.float64(0.0)),
 (358, np.float64(0.06629935441317959)),
 (359, np.float64(0.035245368842512066)),
 (360, np.float64(0.0)),
 (361, np.float64(0.05797710356524483)),
 (362, np.float64(0.10141851056742199)),
 (363, np.float64(0.09035079029052512)),
 (364, np.float64(0.026398183867422733)),
 (365, np.float64(0.08451542547285165)),
 (366, np.float64(0.061721339984836754)),
 (367, np.float64(0.0)),
 (368, np.float64(0.13801311186847084)),
 (369, np.float64(0.1449427589131121)),
 (370, np.float64(0.05884898863364997)),
 (371, np.float64(0.10559273546969093)),
 (372, np.float64(0.055577001437672836)),
 (373, np.float64(0.1938916835823703)),
 (374, np.float64(0.04517539514526256)),
 (375, np.float64(0.04401188481356615)),
 (376, np.float64(0.04931136727215379)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.05375170309743496)),
 (380, np.float64(0.029880715233359837)),
 (381, np.float64(0.09376144618769908)),
 (382, np.float64(0.0)),
 (383, np.float64(0.052164053095730106)),
 (384, np.float64(0.03450327796711771)),
 (385, np.float64(0.0)),
 (386, np.float64(0.02366905341655754)),
 (387, np.float64(0.02817180849095055)),
 (388, np.float64(0.0)),
 (389, np.float64(0.11065666703449761)),
 (390, np.float64(0.028988551782622416)),
 (391, np.float64(0.06195121541733006)),
 (392, np.float64(0.033149677206589796)),
 (393, np.float64(0.0)),
 (394, np.float64(0.02742042485535409)),
 (395, np.float64(0.05884898863364997)),
 (396, np.float64(0.024397501823713332)),
 (397, np.float64(0.05797710356524483)),
 (398, np.float64(0.0)),
 (399, np.float64(0.02672612419124244)),
 (400, np.float64(0.1057361065275362)),
 (401, np.float64(0.035245368842512066)),
 (402, np.float64(0.061721339984836754)),
 (403, np.float64(0.11194341570991125)),
 (404, np.float64(0.06761234037828133)),
 (405, np.float64(0.030358837035945812)),
 (406, np.float64(0.02219483808092376)),
 (407, np.float64(0.02238868314198225)),
 (408, np.float64(0.03688555567816587)),
 (409, np.float64(0.0)),
 (410, np.float64(0.1019294382875251)),
 (411, np.float64(0.057142857142857134)),
 (412, np.float64(0.10432810619146021)),
 (413, np.float64(0.14085904245475275)),
 (414, np.float64(0.033149677206589796)),
 (415, np.float64(0.07166893746324661)),
 (416, np.float64(0.05797710356524483)),
 (417, np.float64(0.03779644730092272)),
 (418, np.float64(0.03984095364447979)),
 (419, np.float64(0.0791945516022682)),
 (420, np.float64(0.12888481555661674)),
 (421, np.float64(0.0)),
 (422, np.float64(0.15118578920369088)),
 (423, np.float64(0.05345224838248488)),
 (424, np.float64(0.04161251892882394)),
 (425, np.float64(0.07244179326244427)),
 (426, np.float64(0.06241877839323591)),
 (427, np.float64(0.030358837035945812)),
 (428, np.float64(0.05894831189188944)),
 (429, np.float64(0.0)),
 (430, np.float64(0.052164053095730106)),
 (431, np.float64(0.026082026547865053)),
 (432, np.float64(0.12598815766974242)),
 (433, np.float64(0.036037498507822355)),
 (434, np.float64(0.0)),
 (435, np.float64(0.040996003084539386)),
 (436, np.float64(0.0)),
 (437, np.float64(0.030358837035945812)),
 (438, np.float64(0.029880715233359837)),
 (439, np.float64(0.033149677206589796)),
 (440, np.float64(0.029424494316824985)),
 (441, np.float64(0.03194382824999699)),
 (442, np.float64(0.05039526306789696)),
 (443, np.float64(0.060717674071891624)),
 (444, np.float64(0.0)),
 (445, np.float64(0.030358837035945812)),
 (446, np.float64(0.027066598098038335)),
 (447, np.float64(0.024655683636076894)),
 (448, np.float64(0.026398183867422733)),
 (449, np.float64(0.060717674071891624)),
 (450, np.float64(0.026398183867422733)),
 (451, np.float64(0.027066598098038335)),
 (452, np.float64(0.03194382824999699)),
 (453, np.float64(0.02817180849095055)),
 (454, np.float64(0.12741179785940637)),
 (455, np.float64(0.02577696311132335)),
 (456, np.float64(0.07171371656006362)),
 (457, np.float64(0.08964214570007951)),
 (458, np.float64(0.048795003647426664)),
 (459, np.float64(0.03688555567816587)),
 (460, np.float64(0.029880715233359837)),
 (461, np.float64(0.1889822365046136)),
 (462, np.float64(0.0)),
 (463, np.float64(0.035245368842512066)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.2114722130550724)),
 (467, np.float64(0.09287269204251442)),
 (468, np.float64(0.03138824102871722)),
 (469, np.float64(0.07171371656006362)),
 (470, np.float64(0.04984447862792268)),
 (471, np.float64(0.0857142857142857)),
 (472, np.float64(0.08827348295047496)),
 (473, np.float64(0.10559273546969093)),
 (474, np.float64(0.0)),
 (475, np.float64(0.06965451903188581)),
 (476, np.float64(0.11065666703449761)),
 (477, np.float64(0.0)),
 (478, np.float64(0.040120542714251965)),
 (479, np.float64(0.09631426606617742)),
 (480, np.float64(0.05345224838248488)),
 (481, np.float64(0.0)),
 (482, np.float64(0.03138824102871722)),
 (483, np.float64(0.14098147537004826)),
 (484, np.float64(0.03779644730092272)),
 (485, np.float64(0.057142857142857134)),
 (486, np.float64(0.059350694118669806)),
 (487, np.float64(0.15511334686589623)),
 (488, np.float64(0.07559289460184544)),
 (489, np.float64(0.0)),
 (490, np.float64(0.15118578920369088)),
 (491, np.float64(0.09035079029052512)),
 (492, np.float64(0.061721339984836754)),
 (493, np.float64(0.020060271357125983)),
 (494, np.float64(0.0)),
 (495, np.float64(0.2267786838055363)),
 (496, np.float64(0.0)),
 (497, np.float64(0.0)),
 (498, np.float64(0.07049073768502413)),
 (499, np.float64(0.0)),
 (500, np.float64(0.028988551782622416)),
 (501, np.float64(0.09035079029052512)),
 (502, np.float64(0.1546617786679401)),
 (503, np.float64(0.08451542547285165)),
 (504, np.float64(0.0)),
 (505, np.float64(0.14754222271266348)),
 (506, np.float64(0.03877833671647406)),
 (507, np.float64(0.2553999031169147)),
 (508, np.float64(0.11952286093343935)),
 (509, np.float64(0.026082026547865053)),
 (510, np.float64(0.10968169942141635)),
 (511, np.float64(0.10350983390135313)),

In [ ]:
def recommend(movie):
    movie_index = new_df[new_df['title']== movie].index[0]
    distances = similarity[movie_index]
    #sort the distances and fetch the first 5 movies
    return